#!/usr/bin/env python3
"""Emit a Ghidra script that names everything we can recover from sohod64.bin.

sohod64.bin arrives stripped, so Ghidra shows a sea of FUN_4xxxxxxx. Two
sources put real names back:

  * the Linux-derived export table, left behind as ___ksymtab+<name> section
    names, each holding its function's address (see syms.py);
  * the CGI dispatch table in .data, mapping URL to handler (see cgimap.py).

Run this to produce a Jython script, then in Ghidra:
    Window > Script Manager > Run Script > sohod_names.py

    python3 ghidra_export.py sohod64.bin > sohod_names.py
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import syms as _syms          # noqa: E402
import cgimap as _cgimap      # noqa: E402

HEADER = '''# Auto-generated by VigorEmu-Toolkit/ghidra_export.py -- do not edit.
# Applies recovered DrayOS symbols to a stripped sohod64.bin.
#
# Load sohod64.bin in Ghidra first. It is ELF32 with EM_AARCH64, i.e. ARM64
# ILP32; if Ghidra does not pick that automatically choose
#   AARCH64:LE:32:ilp32   (or AARCH64:LE:64:v8A and set the image base)
# and confirm the image base is 0x40000000.
# @category DrayOS
from ghidra.program.model.symbol import SourceType

_fm = currentProgram.getFunctionManager()
_af = currentProgram.getAddressFactory().getDefaultAddressSpace()
_named = 0
_made = 0
_failed = 0


def _apply(addr, name):
    global _named, _made, _failed
    try:
        a = _af.getAddress(addr)
        f = _fm.getFunctionAt(a)
        if f is None:
            f = createFunction(a, name)
            if f is not None:
                _made += 1
        if f is None:
            # not decodable as a function; still drop a label
            createLabel(a, name, True)
            _named += 1
            return
        f.setName(name, SourceType.USER_DEFINED)
        _named += 1
    except Exception:
        _failed += 1


NAMES = [
'''

FOOTER = '''
]

for _addr, _name in NAMES:
    _apply(_addr, _name)

print("[sohod_names] %d named, %d functions created, %d failed"
      % (_named, _made, _failed))
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--anchor", default="wlogin.cgi")
    a = ap.parse_args()

    d = _cgimap.load(a.image)

    entries = []
    # 1. exported symbols
    for name, addr in sorted(_syms.recover(a.image).items()):
        clean = "".join(c if (c.isalnum() or c == "_") else "_" for c in name)
        entries.append((addr, clean))

    # 2. CGI handlers -- prefix so they group together in the symbol tree
    seen = set(addr for addr, _ in entries)
    for table in _cgimap.find_tables(d, a.anchor):
        for _ent, nm, hnd, _flags in table:
            if hnd in seen:
                continue
            seen.add(hnd)
            stem = nm[:-4].replace(".", "_").replace("-", "_")
            entries.append((hnd, "cgi_%s" % stem))

    sys.stdout.write(HEADER)
    for addr, name in entries:
        sys.stdout.write("    (0x%08x, %r),\n" % (addr, name))
    sys.stdout.write(FOOTER)
    print("emitted %d names" % len(entries), file=sys.stderr)


if __name__ == "__main__":
    main()
